module.exports = [
    {
        code: 'ara',
        translations: {
            ara: 'عربى',
            eng: 'Arabic',
            fre: 'Arabe',
            rus: 'Арабский',
            spa: 'ara(spa)',
            chi: 'ara(chi)',
            hin: 'ara(hin)',
            por: 'ara(por)',
            ben: 'ara(ben)',
            jpn: 'ara(jpn)',
            ger: 'ara(ger)',
            kor: 'ara(kor)',
            tur: 'ara(tur)',
            tam: 'ara(tam)',
            lah: 'ara(lah)',
        },
    },
    {
        code: 'eng',
        translations: {
            ara: 'الإنجليزية',
            eng: 'English',
            fre: 'Anglais',
            rus: 'Английский',
            spa: 'eng(spa)',
            chi: 'eng(chi)',
            hin: 'eng(hin)',
            por: 'eng(por)',
            ben: 'eng(ben)',
            jpn: 'eng(jpn)',
            ger: 'eng(ger)',
            kor: 'eng(kor)',
            tur: 'eng(tur)',
            tam: 'eng(tam)',
            lah: 'eng(lah)',
        },
    },
    {
        code: 'fre',
        translations: {
            ara: 'فرنسي',
            eng: 'French',
            fre: 'Français',
            rus: 'Французский',
            spa: 'fre(spa)',
            chi: 'fre(chi)',
            hin: 'fre(spa)',
            por: 'fre(por)',
            ben: 'fre(ben)',
            jpn: 'fre(jpn)',
            ger: 'fre(ger)',
            kor: 'fre(kor)',
            tur: 'fre(tur)',
            tam: 'fre(tam)',
            lah: 'fre(lah)',
        },
    },
    {
        code: 'rus',
        translations: {
            ara: 'الروسية',
            eng: 'Russian',
            fre: 'Russe',
            rus: 'Русский',
            spa: 'rus(spa)',
            chi: 'rus(chi)',
            hin: 'rus(hin)',
            por: 'rus(por)',
            ben: 'rus(ben)',
            jpn: 'rus(jpn)',
            ger: 'rus(ger)',
            kor: 'rus(kor)',
            tur: 'rus(tur)',
            tam: 'rus(tam)',
            lah: 'rus(lah)',
        },
    },
    {
        code: 'spa',
        translations: {
            ara: 'الأسبانية',
            eng: 'Spanish',
            fre: 'Espagnol',
            rus: 'Испанский',
            ben: 'spa(ben)',
            chi: 'spa(chi)',
            ger: 'spa(ger)',
            hin: 'spa(hin)',
            jpn: 'spa(jpn)',
            kor: 'spa(kor)',
            lah: 'spa(lah)',
            por: 'spa(por)',
            spa: 'spa(spa)',
            tam: 'spa(tam)',
            tur: 'spa(tur)',
        },
    },
    {
        code: 'chi',
        translations: {
            ara: 'الصينية',
            eng: 'Chinese',
            fre: 'Chinois',
            rus: 'Китайский',
            ben: 'chi(ben)',
            chi: 'chi(chi)',
            ger: 'chi(ger)',
            hin: 'chi(hin)',
            jpn: 'chi(jpn)',
            kor: 'chi(kor)',
            lah: 'chi(lah)',
            por: 'chi(por)',
            spa: 'chi(spa)',
            tam: 'chi(tam)',
            tur: 'chi(tur)',
        },
    },
    {
        code: 'hin',
        translations: {
            ara: 'الهندية',
            eng: 'Hindi',
            fre: 'Hindi',
            rus: 'Хинди',
            ben: 'hin(ben)',
            chi: 'hin(chi)',
            ger: 'hin(ger)',
            hin: 'hin(hin)',
            jpn: 'hin(jpn)',
            kor: 'hin(kor)',
            lah: 'hin(lah)',
            por: 'hin(por)',
            spa: 'hin(spa)',
            tam: 'hin(tam)',
            tur: 'hin(tur)',
        },
    },
    {
        code: 'por',
        translations: {
            ara: 'البرتغالية',
            eng: 'Portuguese',
            fre: 'Portugais',
            rus: 'Португальский',
            ben: 'por(ben)',
            chi: 'por(chi)',
            ger: 'por(ger)',
            hin: 'por(hin)',
            jpn: 'por(jpn)',
            kor: 'por(kor)',
            lah: 'por(lah)',
            por: 'por(por)',
            spa: 'por(spa)',
            tam: 'por(tam)',
            tur: 'por(tur)',
        },
    },
    {
        code: 'ben',
        translations: {
            ara: 'بنغالي',
            eng: 'Bengali',
            fre: 'Bengali',
            rus: 'Бенгальский',
            ben: 'ben(ben)',
            chi: 'ben(chi)',
            ger: 'ben(ger)',
            hin: 'ben(hin)',
            jpn: 'ben(jpn)',
            kor: 'ben(kor)',
            lah: 'ben(lah)',
            por: 'ben(por)',
            spa: 'ben(spa)',
            tam: 'ben(tam)',
            tur: 'ben(tur)',
        },
    },
    {
        code: 'jpn',
        translations: {
            ara: 'اليابانية',
            eng: 'Japanese',
            fre: 'Japonais',
            rus: 'Японский',
            ben: 'jpn(ben)',
            chi: 'jpn(chi)',
            ger: 'jpn(ger)',
            hin: 'jpn(hin)',
            jpn: 'jpn(jpn)',
            kor: 'jpn(kor)',
            lah: 'jpn(lah)',
            por: 'jpn(por)',
            spa: 'jpn(spa)',
            tam: 'jpn(tam)',
            tur: 'jpn(tur)',
        },
    },
    {
        code: 'ger',
        translations: {
            ara: 'ألماني',
            eng: 'German',
            fre: 'Allemand',
            rus: 'Немецкий',
            ben: 'ger(ben)',
            chi: 'ger(chi)',
            ger: 'ger(ger)',
            hin: 'ger(hin)',
            jpn: 'ger(jpn)',
            kor: 'ger(kor)',
            lah: 'ger(lah)',
            por: 'ger(por)',
            spa: 'ger(spa)',
            tam: 'ger(tam)',
            tur: 'ger(tur)',
        },
    },
    {
        code: 'kor',
        translations: {
            ara: 'كوري',
            eng: 'Korean',
            fre: 'Coréen',
            rus: 'Корейский',
            ben: 'kor(ben)',
            chi: 'kor(chi)',
            ger: 'kor(ger)',
            hin: 'kor(hin)',
            jpn: 'kor(jpn)',
            kor: 'kor(kor)',
            lah: 'kor(lah)',
            por: 'kor(por)',
            spa: 'kor(spa)',
            tam: 'kor(tam)',
            tur: 'kor(tur)',
        },
    },
    {
        code: 'tur',
        translations: {
            ara: 'اللغة التركية',
            eng: 'Turkish',
            fre: 'Turc',
            rus: 'Турецкий',
            ben: 'tur(ben)',
            chi: 'tur(chi)',
            ger: 'tur(ger)',
            hin: 'tur(hin)',
            jpn: 'tur(jpn)',
            kor: 'tur(kor)',
            lah: 'tur(lah)',
            por: 'tur(por)',
            spa: 'tur(spa)',
            tam: 'tur(tam)',
            tur: 'tur(tur)',
        },
    },
    {
        code: 'tam',
        translations: {
            ara: 'التاميل',
            eng: 'Tamil',
            fre: 'Tamil',
            rus: 'Тамил',
            ben: 'tam(ben)',
            chi: 'tam(chi)',
            ger: 'tam(ger)',
            hin: 'tam(hin)',
            jpn: 'tam(jpn)',
            kor: 'tam(kor)',
            lah: 'tam(lah)',
            por: 'tam(por)',
            spa: 'tam(spa)',
            tam: 'tam(tam)',
            tur: 'tam(tur)',
        },
    },
    {
        code: 'lah',
        translations: {
            ara: 'الأردية',
            eng: 'Lahnda',
            fre: 'Lahnda',
            rus: 'Урду',
            ben: 'lah(ben)',
            chi: 'lah(chi)',
            ger: 'lah(ger)',
            hin: 'lah(hin)',
            jpn: 'lah(jpn)',
            kor: 'lah(kor)',
            lah: 'lah(lah)',
            por: 'lah(por)',
            spa: 'lah(spa)',
            tam: 'lah(tam)',
            tur: 'lah(tur)',
        },
    },
];
