module.exports = [
    {
        name: 'math',
        level: 1,
        translations: {
            ara: 'الرياضيات',
            eng: 'Mathematics',
            fre: 'Mathématiques',
            rus: 'Математика',
            spa: 'Matemáticas',
            chi: '數學',
            hin: 'अंक शास्त्र',
            por: 'Matemática',
            ben: 'অংক',
            jpn: '数学',
            ger: 'Mathematik',
            kor: '수학',
            tur: 'Matematik',
            tam: 'கணிதம்',
            lah: 'ریاضی',
        },
    },
    {
        name: 'chemistry',
        level: 1,
        translations: {
            ara: 'كيمياء',
            eng: 'Chemistry',
            fre: 'Chimie',
            rus: 'Химия',
            spa: 'Química',
            chi: '化學',
            hin: 'रसायन विज्ञान',
            por: 'Química',
            ben: 'রসায়ন',
            jpn: '化学',
            ger: 'Chemie',
            kor: '화학',
            tur: 'Kimya',
            tam: 'வேதியியல்',
            lah: 'کیمسٹری',
        },
    },
    {
        name: 'physics',
        level: 1,
        translations: {
            ara: 'علوم فيزيائية',
            eng: 'Physics',
            fre: 'Physique',
            rus: 'Физика',
            spa: 'Física',
            chi: '物理學',
            hin: 'भौतिक विज्ञान',
            por: 'Física',
            ben: 'পদার্থবিদ্যা',
            jpn: '物理',
            ger: 'Physik',
            kor: '물리학',
            tur: 'Fizik',
            tam: 'இயற்பியல்',
            lah: 'طبیعیات',
        },
    },
    {
        name: 'english',
        level: 1,
        translations: {
            ara: 'الإنجليزية',
            eng: 'English',
            fre: 'Anglais',
            rus: 'Английский',
            spa: 'Inglés',
            chi: '英語',
            hin: 'अंग्रेज़ी',
            por: 'Inglês',
            ben: 'ইংরেজি',
            jpn: '英語',
            ger: 'Englisch',
            kor: '영어',
            tur: 'Ingilizce',
            tam: 'ஆங்கிலம்',
            lah: 'انگریزی',
        },
    },
    {
        name: 'arabic',
        level: 1,
        translations: {
            ara: 'عربى',
            eng: 'Arabic',
            fre: 'Arabe',
            rus: 'Арабский',
            spa: 'ara(spa)',
            chi: 'ara(chi)',
            hin: 'ara(hin)',
            por: 'ara(por)',
            ben: 'ara(ben)',
            jpn: 'ara(jpn)',
            ger: 'ara(ger)',
            kor: 'ara(kor)',
            tur: 'ara(tur)',
            tam: 'ara(tam)',
            lah: 'ara(lah)',
        },
    },
    {
        name: 'calc1',
        level: 101,
        translations: {
            ara: ' حصاة المثانة أو الكلية',
            eng: 'Calculus I',
            fre: 'cacl1(fre)',
            rus: 'cacl1(rus)',
            spa: 'cacl1(spa)',
            chi: 'cacl1(chi)',
            hin: 'cacl1(hin)',
            por: 'cacl1(por)',
            ben: 'cacl1(ben)',
            jpn: 'cacl1(jpn)',
            ger: 'cacl1(ger)',
            kor: 'cacl1(kor)',
            tur: 'cacl1(tur)',
            tam: 'cacl1(tam)',
            lah: 'cacl1(lah)',
        },
    },
    {
        name: 'calc2',
        level: 102,
        base: 'calc1',
        translations: {
            ara: ' حصاة المثانة أو الكلية',
            eng: 'Calculus II',
            fre: 'cacl2(fre)',
            rus: 'cacl2(rus)',
            spa: 'cacl2(spa)',
            chi: 'cacl2(chi)',
            hin: 'cacl2(hin)',
            por: 'cacl2(por)',
            ben: 'cacl2(ben)',
            jpn: 'cacl2(jpn)',
            ger: 'cacl2(ger)',
            kor: 'cacl2(kor)',
            tur: 'cacl2(tur)',
            tam: 'cacl2(tam)',
            lah: 'cacl2(lah)',
        },
    },
    {
        name: 'calc3',
        level: 103,
        base: 'calc1',
        translations: {
            ara: ' حصاة المثانة أو الكلية',
            eng: 'Calculus III',
            fre: 'cacl3(fre)',
            rus: 'cacl3(rus)',
            spa: 'cacl3(spa)',
            chi: 'cacl3(chi)',
            hin: 'cacl3(hin)',
            por: 'cacl3(por)',
            ben: 'cacl3(ben)',
            jpn: 'cacl3(jpn)',
            ger: 'cacl3(ger)',
            kor: 'cacl3(kor)',
            tur: 'cacl3(tur)',
            tam: 'cacl3(tam)',
            lah: 'cacl3(lah)',
        },
    },
    {
        name: 'physics1',
        level: 101,
        base: 'physics',
        translations: {
            ara: '1 علوم فيزيائية',
            eng: 'Physics I',
            fre: 'Physique I',
            rus: 'Физика I',
            spa: 'Física I',
            chi: '物理學 I',
            hin: 'भौतिक विज्ञान I',
            por: 'Física I',
            ben: 'পদার্থবিদ্যা I',
            jpn: '物理 I',
            ger: 'Physik I',
            kor: '물리학 I',
            tur: 'Fizik I',
            tam: 'இயற்பியல் I',
            lah: '1 طبیعیات',
        },
    },
    {
        name: 'physics2',
        level: 102,
        base: 'physics',
        translations: {
            ara: '2 علوم فيزيائية',
            eng: 'Physics II',
            fre: 'Physique II',
            rus: 'Физика II',
            spa: 'Física II',
            chi: '物理學 II',
            hin: 'भौतिक विज्ञान II',
            por: 'Física II',
            ben: 'পদার্থবিদ্যা II',
            jpn: '物理 II',
            ger: 'Physik II',
            kor: '물리학 II',
            tur: 'Fizik II',
            tam: 'இயற்பியல் II',
            lah: '2 طبیعیات',
        },
    },
    {
        name: 'linAlg',
        level: 101,
        translations: {
            ara: 'الجبر الخطي',
            eng: 'Linear Algebra',
            fre: 'linAlg(fre)',
            rus: 'linAlg(rus)',
            spa: 'linAlg(spa)',
            chi: 'linAlg(chi)',
            hin: 'linAlg(hin)',
            por: 'linAlg(por)',
            ben: 'linAlg(ben)',
            jpn: 'linAlg(jpn)',
            ger: 'linAlg(ger)',
            kor: 'linAlg(kor)',
            tur: 'linAlg(tur)',
            tam: 'linAlg(tam)',
            lah: 'linAlg(lah)',
        },
    },
    {
        name: 'difEq',
        level: 101,
        translations: {
            ara: 'المعادلات التفاضلية',
            eng: 'Differential Equations',
            fre: 'difEq(fre)',
            rus: 'difEq(rus)',
            spa: 'difEq(spa)',
            chi: 'difEq(chi)',
            hin: 'difEq(hin)',
            por: 'difEq(por)',
            ben: 'difEq(ben)',
            jpn: 'difEq(jpn)',
            ger: 'difEq(ger)',
            kor: 'difEq(kor)',
            tur: 'difEq(tur)',
            tam: 'difEq(tam)',
            lah: 'difEq(lah)',
        },
    },
    {
        name: 'statics',
        level: 101,
        translations: {
            ara: 'علم الإحصاء',
            eng: 'Statics',
            fre: 'statics(fre)',
            rus: 'statics(rus)',
            spa: 'statics(spa)',
            chi: 'statics(chi)',
            hin: 'statics(hin)',
            por: 'statics(por)',
            ben: 'statics(ben)',
            jpn: 'statics(jpn)',
            ger: 'statics(ger)',
            kor: 'statics(kor)',
            tur: 'statics(tur)',
            tam: 'statics(tam)',
            lah: 'statics(lah)',
        },
    },
    {
        name: 'dynamics',
        level: 101,
        translations: {
            ara: 'الديناميكا علم الحيل',
            eng: 'Dynamics',
            fre: 'dynamics(fre)',
            rus: 'dynamics(rus)',
            spa: 'dynamics(spa)',
            chi: 'dynamics(chi)',
            hin: 'dynamics(hin)',
            por: 'dynamics(por)',
            ben: 'dynamics(ben)',
            jpn: 'dynamics(jpn)',
            ger: 'dynamics(ger)',
            kor: 'dynamics(kor)',
            tur: 'dynamics(tur)',
            tam: 'dynamics(tam)',
            lah: 'dynamics(lah)',
        },
    },
    {
        name: 'arabic1',
        level: 101,
        base: 'arabic',
        translations: {
            ara: 'العربية (القواعد ، الكتابة)',
            eng: 'Arabic (Grammar, Writing)',
            fre: 'arabic1(fre)',
            rus: 'arabic1(rus)',
            spa: 'arabic1(spa)',
            chi: 'arabic1(chi)',
            hin: 'arabic1(hin)',
            por: 'arabic1(por)',
            ben: 'arabic1(ben)',
            jpn: 'arabic1(jpn)',
            ger: 'arabic1(ger)',
            kor: 'arabic1(kor)',
            tur: 'arabic1(tur)',
            tam: 'arabic1(tam)',
            lah: 'arabic1(lah)',
        },
    },
    {
        name: 'english1',
        base: 'english',
        level: 101,
        translations: {
            ara: 'اللغة الإنجليزية (القواعد ، الكتابة)',
            eng: 'English (Grammar, Writing)',
            fre: 'english1(fre)',
            rus: 'english1(rus)',
            spa: 'english1(spa)',
            chi: 'english1(chi)',
            hin: 'english1(hin)',
            por: 'english1(por)',
            ben: 'english1(ben)',
            jpn: 'english1(jpn)',
            ger: 'english1(ger)',
            kor: 'english1(kor)',
            tur: 'english1(tur)',
            tam: 'english1(tam)',
            lah: 'english1(lah)',
        },
    },
    {
        name: 'chemistry1',
        base: 'chemistry',
        level: 101,
        translations: {
            ara: 'I كيمياء',
            eng: 'Chemistry I',
            fre: 'chemistry1(fre)',
            rus: 'chemistry1(rus)',
            spa: 'chemistry1(spa)',
            chi: 'chemistry1(chi)',
            hin: 'chemistry1(hin)',
            por: 'chemistry1(por)',
            ben: 'chemistry1(ben)',
            jpn: 'chemistry1(jpn)',
            ger: 'chemistry1(ger)',
            kor: 'chemistry1(kor)',
            tur: 'chemistry1(tur)',
            tam: 'chemistry1(tam)',
            lah: 'chemistry1(lah)',
        },
    },
    {
        name: 'chemistry2',
        base: 'chemistry',
        level: 102,
        translations: {
            ara: 'II كيمياء',
            eng: 'Chemistry II',
            fre: 'chemistry2(fre)',
            rus: 'chemistry2(rus)',
            spa: 'chemistry2(spa)',
            chi: 'chemistry2(chi)',
            hin: 'chemistry2(hin)',
            por: 'chemistry2(por)',
            ben: 'chemistry2(ben)',
            jpn: 'chemistry2(jpn)',
            ger: 'chemistry2(ger)',
            kor: 'chemistry2(kor)',
            tur: 'chemistry2(tur)',
            tam: 'chemistry2(tam)',
            lah: 'chemistry2(lah)',
        },
    },
    {
        name: 'thermodynamics',
        level: 101,
        translations: {
            ara: 'الديناميكا الحرارية',
            eng: 'Thermodynamics',
            fre: 'thermodynamics(fre)',
            rus: 'thermodynamics(rus)',
            spa: 'thermodynamics(spa)',
            chi: 'thermodynamics(chi)',
            hin: 'thermodynamics(hin)',
            por: 'thermodynamics(por)',
            ben: 'thermodynamics(ben)',
            jpn: 'thermodynamics(jpn)',
            ger: 'thermodynamics(ger)',
            kor: 'thermodynamics(kor)',
            tur: 'thermodynamics(tur)',
            tam: 'thermodynamics(tam)',
            lah: 'thermodynamics(lah)',
        },
    },
];
