module.exports = {
    id: Number,
    firstName: String,
    lastName: String,
    country: String,
    email: String,
    city: String,
    university: String,
    grade: Number,
    countryCode: String,
    countCards: Number,
    lastPhoneDigits: String,
    postalCode: String,
    address: String,
    state: String,
    promoCode: String,
    profileImageUrl: 'UrlPhoto',
    defaultCardInfo: 'CardInfo',
    tutorStatus: {
        constructor: String,
        dbName: 'status',
    },
    countLesson: Number,
    rate: Number,
};
